[package]
name = "gambit_client"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 2

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0"
quiche = "0.16"
mio = { version = "0.8", features = ["net", "os-poll"] }
url = "1"
log = { version = "0.4", features = ["std"] }
ring = "0.16"
env_logger = "0.9.0"
sysinfo = "0.20.4"
obfstr = "0.3.0"
ntapi = "0.4.0"
byteorder = "1.4.3"
hex = "0.4"
winapi = "0.3.9"

[dependencies.windows-sys]
version = "0.36.1"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_System_Kernel",
    "Win32_System_WindowsProgramming",
    "Win32_System_SystemServices",
    "Win32_System_Diagnostics_Debug"
]